import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "population trend graph",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <header className="bg-blue-200 shadow-md px-4 py-2">
          <h2 className="font-bold">人口推移グラフ</h2>
        </header>
        {children}
      </body>
    </html>
  );
}
